### ISSUE TITLE
Potentially redundant use of github ref context variable

### ISSUE THREAD

**Issue by komish** [openshift-helm-charts/development#294]
It seems that we're setting the GITHUB_REF environment variable to the value of github.ref at the workflow level, but I don't believe this to be required.

https://github.com/openshift-helm-charts/development/blob/main/.github/workflows/build.yml#L468C18-L468C18

It's possible https://github.com/openshift-helm-charts/development/pull/289 resolves this, in which case we can close this issue out.

Creating this so we don't forget to investigate.

**Comment by mgoerens** [comment]
```
$ grep -rn "GITHUB_REF" scripts/

```

I will change this as part of #289, as I anyway refactor things quite a bit and such a small change can be added there IMO.

**Comment by mgoerens** [comment]
I didn't realize that `$GITHUB_REF` was available as a environment variable already, so this change is even more trivial than I thought. Added to #289.
